name: Check Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Configure .npmrc for Azure Artifacts
        uses: Vizir/action-azure-artifacts-config-npmrc@1.0
        with:
          organization: vizir-banking
          project: vizir-banking
          feeds: vizir-banking,vb-libs
          username: vizir-banking
          token: ${{ secrets.AZURE_PAT }}

      - name: Run CI
        run: |
          yarn install
          yarn lint
          yarn release
